### PR TITLE
converted into a unity package

### PR DESCRIPTION
**Pull request by andrew-raphael-lukasik**
Hi,

I was interested in testing your project but merging two projects is messy while it's cleaner to just install a package, inspect, easy to remove too. So I made a git package on [that UPM branch](https://github.com/andrew-raphael-lukasik/unity-asm-explorer-package/tree/upm) from it. It's not meant to be merged into `master` branch ofc but to live on dedicated one.

This is just a FYI message.

 Have a good day

### CODE REVIEW

**Comment by sschoener** [comment]
Thanks! When using this with Unity, you can use [this](https://docs.unity3d.com/Manual/upm-git.html#subfolder) to also add a package from a subdirectory of a git repository. E.g. in this case you'd have to use
```
{
  "dependencies": {
    "com.s-schoener.asmexplorer": "https://github.com/sschoener/unity-asm-explorer-package.git?path=/Packages/com.s-schoener.asmexplorer"
  }
}
```
I've updated the main ReadMe to include this information :)

**Comment by andrew-raphael-lukasik** [comment]
Good idea, didn't know that. But I see that this results in the same compilation errors (`Unity 2021.2.8`) I was trying to patch with my "port" i.e: `HttpUtility` not found and `Collections` 1.1 causing chaos as well.
Oh well, what can we do, compatibility is not a big strength for Unity c# lately.

**Comment by sschoener** [comment]
I am curious: What chaos is `Collections 1.1` causing in 2021.2?
For the `HttpUtility`: I think this might be a difference between targeting .NET Framework 4 and .NET Standard. I have tested the package with 2020.3 and 2022.2 (an internal version that you likely do not have access to yet), so it's interesting that 2021.2 doesn't work.

**Comment by andrew-raphael-lukasik** [comment]
> What chaos is `Collections 1.1` causing in 2021.2?

It triggers a compatibility gridlock between `Collections`, `Jobs` & `Entities`  packages in my projects. `Collections 1.1` wont compile with `Jobs 0.8` and totally bombs `Entities 0.17`.
Idk, there might be some perfect version match between them possible but that knowledge is arcane to me.

> I think this might be a difference between targeting .NET Framework 4 and .NET Standard

That seems to be parallel with what I've come to figure out too. I patched this over by adding 2 x dll files ( [Mono.HttpUtility.dll](https://github.com/andrew-raphael-lukasik/unity-asm-explorer-package/commit/0019f29fc52994f0ba09df57be80fc68be368261) & [System.Runtime.CompilerServices.Unsafe.dll](https://github.com/sschoener/unity-asm-explorer-package/pull/2/commits/1c499ba3736e70ec2b99f4e12e2cf033441948a2) ).

**Comment by sschoener** [comment]
> Idk, there might be some perfect version match between them possible but that knowledge is arcane to me.

Ah yes, Collections 1.1 isn't compatible with Entities 0.17, unfortunately. Entities 0.50 will be compatible with Collections 1.x .

> That seems to be parallel with what I've come to figure out too. I patched this over by adding an auxiliary mono dll.

Great! Mind if I put this into the main branch with a conditional define?

**Comment by andrew-raphael-lukasik** [comment]
Sure! sounds good to me
Also - I edited my prev post because there were actually 2 dlls involved in my patch there
